### ISSUE TITLE
ExecJS::ProgramError in rake assets:precompile with 3.2.0

### ISSUE THREAD

**Issue by wrburgess** [daytonn/jskit_rails#3] opened 2014-12-06 01:53 UTC
Attempted to push `3.2.0` to Heroku and received this error. Rolled back to `3.0.0` and deployment passed. Gem introduced by @angeleah for additional reference

```
ExecJS::ProgramError: Unexpected token: name (Events) (line: 3, col: 7, pos: 34)
Error
at new JS_Parse_Error (/tmp/execjs20141206-768-1kk7n2tjs:2357:10623)
at js_error (/tmp/execjs20141206-768-1kk7n2tjs:2357:10842)
at croak (/tmp/execjs20141206-768-1kk7n2tjs:2357:19067)
at token_error (/tmp/execjs20141206-768-1kk7n2tjs:2357:19204)
at unexpected (/tmp/execjs20141206-768-1kk7n2tjs:2357:19292)
at semicolon (/tmp/execjs20141206-768-1kk7n2tjs:2357:19765)
at simple_statement (/tmp/execjs20141206-768-1kk7n2tjs:2357:22538)
at /tmp/execjs20141206-768-1kk7n2tjs:2357:20534
at /tmp/execjs20141206-768-1kk7n2tjs:2357:19938
at /tmp/execjs20141206-768-1kk7n2tjs:2357:31926
(in /tmp/build_004f773740eb10ea347e931dbc9a6af9/vendor/bundle/ruby/2.1.0/gems/jskit_rails-3.2.0/app/assets/javascripts/jskit/application.js.es6)/tmp/build_004f773740eb10ea347e931dbc9a6af9/vendor/bundle/ruby/2.1.0/gems/execjs-2.2.2/lib/execjs/external_runtime.rb:64:in `extract_result'
/tmp/build_004f773740eb10ea347e931dbc9a6af9/vendor/bundle/ruby/2.1.0/gems/execjs-2.2.2/lib/execjs/external_runtime.rb:29:in `exec'
```

**Comment by daytonn** [comment] 2015-01-06 01:59
Duplicate of #4

**Closed by daytonn** 2015-01-06 01:59 UTC
